version: '3'
services:
  postgres:
    image: "postgres:12.4"
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
  esearch:
    image: elasticsearch:7.7.1
    container_name: skills-data-processor-es_es
    ports:
      - ${ES_PORT}:${ES_PORT}
    environment:
      - discovery.type=single-node

volumes:
  database-data:

